--2021.01.27.목

--SYSTEM

--권한 주기

GRANT CREATE USER TO kim;

SELECT * FROM DBA_USERS;

--비번 잘못 입력시 LOCKED 계정이 잠김.

ALTER USER TEST ACCOUNT LOCK;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO TEST;--권한주기

ALTER USER TEST ACCOUNT UNLOCK;

ALTER USER TEST IDENTIFIED BY ABC ACCOUNT UNLOCK;--ID도 같이 바꾸고 싶음

REVOKE CREATE USER FROM kim;--권한 뺏기

--권한의 종류
/*
SYSTEM 권한 : DATA BASE의 OBJECT들을
			  생성(CREATE), 수정(ALTER), 삭제(DROP) 할 수 있는 권한
			  DBA(관리자) -> USERS(일반사용자)
			  
OBJECT 권한 : OBJECT 내용을 추가(INSERT), 변경(UPDATE), 삭제(DELETE), 검색(SELECT)를
			  할 수 있는 권한
			  USERS(일반사용자) -> USERS(일반사용자)
			  EX) kim -> lee
			  
OBJECT: TABLE, SEQUENCE, VIEW, DOMAIN
*/

--SYSTEM 권한
SELECT * FROM SYSTEM_PRIVILEGE_MAP;
--권한을 

GRANT CREATE SESSION TO SUZI;
GRANT CREATE SESSION, RESOURCE, UNLIMITED TABLESPACE TO SUZI;

REVOKE RESOURCE, UNLIMITED TABLESPACE FROM SUZI;

--다른 사용자가 쓰게 끔 만들 거야앗

--OBJECT 권한 : kim에서 해보자. 물론 SYS에서도 가능


--ROLE
--KIM이라는 사용자가 ROLE 권한 만들 수 있음
GRANT CREATE ROLE TO KIM;

CREATE ROLE MANAGER;
--DROP ROLE MANAGER1;
GRANT CREATE USER, CREATE VIEW TO MANAGER; --권한이 2개가 ?

SELECT * FROM DBA_ROLES;--DICTIONARY는 항상 끝에 S 붙임

--관리자로 권한을 줄 수 있다(관리자 변경 가능)

SELECT * FROM ROLE_SYS_PRIVS;

SELECT * FROM ROLE_SYS_PRIVS
WHERE ROLE = 'MANAGER';

--KIM에서 해야?
--SELECT * FROM ROLE_SYS_PRIVS
--WHERE ROLE IN ('CONNECT', 'RESOURCE');

GRANT MANAGER TO SUZI;--(CREATE VIEW, CREATE USERS)을 권한을 SUZI에게 넣음

REVOKE MANAGER FROM SUZI;

--ROLE은 무조건 EXIT 해야?. 나가기 전까지는 유지?.